version: '3.8'
services:
  app:
    container_name: express_app_fullstack
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db2
    # command: ["sh", "-c", "./wait-for-it.sh db:3306 -- npm start"]
    entrypoint: ["./wait-for-it.sh", "postgres_db2:5432", "--", "npm", "start"]
    # command: [ "npm", "start" ]
    # command: ["sh", "-c", "./wait-for-it.sh -t db:3306 -- npm start"]
    environment:
      - DB_HOST=postgres_db2
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=Resource_sharing
    networks:
      - my_network
  postgres_db2:
    container_name: postgres_db2
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'Resource_sharing'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initDB.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - my_network
volumes:
  db_data:

networks:
  my_network:
    driver: bridge
